### ISSUE TITLE
I Have Error When Try To Run compodoc Comand

### ISSUE THREAD

**Issue by amirzenoozi** [compodoc/compodoc-demo-todomvc-angular#9]
When I Try To Run the compodoc comand I Get Below Error:

```bash
$ npm run compodoc

> compodoc-demo-todomvc-angular@0.0.0 compodoc E:\Web Application\compodoc-demo-todomvc-angular
> compodoc --config .compodocrc

E:\Web Application\compodoc-demo-todomvc-angular\node_modules\cosmiconfig\dist\readFile.js:38
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'E:\Web Application\compodoc-demo-todomvc-angular\.compodocrc'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Function.readFileSync [as sync] (E:\Web Application\compodoc-demo-todomvc-angular\node_modules\cosmiconfig\dist\readFile.js:33:15)
    at E:\Web Application\compodoc-demo-todomvc-angular\node_modules\cosmiconfig\dist\createExplorer.js:291:32
    at cacheWrapper (E:\Web Application\compodoc-demo-todomvc-angular\node_modules\cosmiconfig\dist\cacheWrapper.js:14:18)
    at Explorer.loadSync (E:\Web Application\compodoc-demo-todomvc-angular\node_modules\cosmiconfig\dist\createExplorer.js:290:12)
    at CliApplication.start (E:\Web Application\compodoc-demo-todomvc-angular\node_modules\@compodoc\compodoc\dist\index-cli.js:179:51)
    at Object.<anonymous> (E:\Web Application\compodoc-demo-todomvc-angular\node_modules\@compodoc\compodoc\bin\index-cli.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\Web Application\\compodoc-demo-todomvc-angular\\.compodocrc'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! compodoc-demo-todomvc-angular@0.0.0 compodoc: `compodoc --config .compodocrc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the compodoc-demo-todomvc-angular@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by pejman-saberin** [comment]
It seems that it is not able to open your file. Add this package. json then you can run npm run compodoc. 
In Angular 9, now I see that I have to specify what folder to watch as well - '-w' means watch the source folder. 
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p tsconfig.json -w ./src -s  --output ../Path To where you want the documentation/documentation --silent"
  },

**Comment by vogloblinsky** [comment]
Sorry @amirzenoozi the npm script "compodoc" is a test for the config file, .compodocrc
